package com.ubs.mycurrency.util;

public enum Currency {
    AED("UAE Dirham", "United Arab Emirates", "AE"),
    AFN("Afghan Afghani", "Afghanistan", "AF"),
    ALL("Albanian Lek", "Albania", "AL"),
    AMD("Armenian Dram", "Armenia", "AM"),
    ANG("Netherlands Antillian Guilder", "Netherlands Antilles", "AN"),
    AOA("Angolan Kwanza", "Angola", "AO"),
    ARS("Argentine Peso", "Argentina", "AR"),
    AUD("Australian Dollar", "Australia", "AU"),
    AWG("Aruban Florin", "Aruba", "AW"),
    AZN("Azerbaijani Manat", "Azerbaijan", "AZ"),
    BAM("Bosnia and Herzegovina Mark", "Bosnia and Herzegovina", "BA"),
    BBD("Barbados Dollar", "Barbados", "BB"),
    BDT("Bangladeshi Taka", "Bangladesh", "BD"),
    BGN("Bulgarian Lev", "Bulgaria", "BG"),
    BHD("Bahraini Dinar", "Bahrain", "BH"),
    BIF("Burundian Franc", "Burundi", "BI"),
    BMD("Bermudian Dollar", "Bermuda", "BM"),
    BND("Brunei Dollar", "Brunei", "BN"),
    BOB("Bolivian Boliviano", "Bolivia", "BO"),
    BRL("Brazilian Real", "Brazil", "BR"),
    BSD("Bahamian Dollar", "Bahamas", "BS"),
    BTN("Bhutanese Ngultrum", "Bhutan", "BT"),
    BWP("Botswana Pula", "Botswana", "BW"),
    BYN("Belarusian Ruble", "Belarus", "BY"),
    BZD("Belize Dollar", "Belize", "BZ"),
    CAD("Canadian Dollar", "Canada", "CA"),
    CDF("Congolese Franc", "Democratic Republic of the Congo", "CD"),
    CHF("Swiss Franc", "Switzerland", "CH"),
    CLP("Chilean Peso", "Chile", "CL"),
    CNY("Chinese Renminbi", "China", "CN"),
    COP("Colombian Peso", "Colombia", "CO"),
    CRC("Costa Rican Colon", "Costa Rica", "CR"),
    CUP("Cuban Peso", "Cuba", "CU"),
    CVE("Cape Verdean Escudo", "Cape Verde", "CV"),
    CZK("Czech Koruna", "Czech Republic", "CZ"),
    DJF("Djiboutian Franc", "Djibouti", "DJ"),
    DKK("Danish Krone", "Denmark", "DK"),
    DOP("Dominican Peso", "Dominican Republic", "DO"),
    DZD("Algerian Dinar", "Algeria", "DZ"),
    EGP("Egyptian Pound", "Egypt", "EG"),
    ERN("Eritrean Nakfa", "Eritrea", "ER"),
    ETB("Ethiopian Birr", "Ethiopia", "ET"),
    EUR("Euro", "European Union", "EU"),
    FJD("Fiji Dollar", "Fiji", "FJ"),
    FKP("Falkland Islands Pound", "Falkland Islands", "FK"),
    FOK("Faroese Króna", "Faroe Islands", "FO"),
    GBP("Pound Sterling", "United Kingdom", "GB"),
    GEL("Georgian Lari", "Georgia", "GE"),
    GGP("Guernsey Pound", "Guernsey", "GG"),
    GHS("Ghanaian Cedi", "Ghana", "GH"),
    GIP("Gibraltar Pound", "Gibraltar", "GI"),
    GMD("Gambian Dalasi", "The Gambia", "GM"),
    GNF("Guinean Franc", "Guinea", "GN"),
    GTQ("Guatemalan Quetzal", "Guatemala", "GT"),
    GYD("Guyanese Dollar", "Guyana", "GY"),
    HKD("Hong Kong Dollar", "Hong Kong", "HK"),
    HNL("Honduran Lempira", "Honduras", "HN"),
    HRK("Croatian Kuna", "Croatia", "HR"),
    HTG("Haitian Gourde", "Haiti", "HT"),
    HUF("Hungarian Forint", "Hungary", "HU"),
    IDR("Indonesian Rupiah", "Indonesia", "ID"),
    ILS("Israeli New Shekel", "Israel", "IL"),
    IMP("Manx Pound", "Isle of Man", "IM"),
    INR("Indian Rupee", "India", "IN"),
    IQD("Iraqi Dinar", "Iraq", "IQ"),
    IRR("Iranian Rial", "Iran", "IR"),
    ISK("Icelandic Króna", "Iceland", "IS"),
    JEP("Jersey Pound", "Jersey", "JE"),
    JMD("Jamaican Dollar", "Jamaica", "JM"),
    JOD("Jordanian Dinar", "Jordan", "JO"),
    JPY("Japanese Yen", "Japan", "JP"),
    KES("Kenyan Shilling", "Kenya", "KE"),
    KGS("Kyrgyzstani Som", "Kyrgyzstan", "KG"),
    KHR("Cambodian Riel", "Cambodia", "KH"),
    KID("Kiribati Dollar", "Kiribati", "KI"),
    KMF("Comorian Franc", "Comoros", "KM"),
    KRW("South Korean Won", "South Korea", "KR"),
    KWD("Kuwaiti Dinar", "Kuwait", "KW"),
    KYD("Cayman Islands Dollar", "Cayman Islands", "KY"),
    KZT("Kazakhstani Tenge", "Kazakhstan", "KZ"),
    LAK("Lao Kip", "Laos", "LA"),
    LBP("Lebanese Pound", "Lebanon", "LB"),
    LKR("Sri Lanka Rupee", "Sri Lanka", "LK"),
    LRD("Liberian Dollar", "Liberia", "LR"),
    LSL("Lesotho Loti", "Lesotho", "LS"),
    LYD("Libyan Dinar", "Libya", "LY"),
    MAD("Moroccan Dirham", "Morocco", "MA"),
    MDL("Moldovan Leu", "Moldova", "MD"),
    MGA("Malagasy Ariary", "Madagascar", "MG"),
    MKD("Macedonian Denar", "North Macedonia", "MK"),
    MMK("Burmese Kyat", "Myanmar", "MM"),
    MNT("Mongolian Tögrög", "Mongolia", "MN"),
    MOP("Macanese Pataca", "Macau", "MO"),
    MRU("Mauritanian Ouguiya", "Mauritania", "MR"),
    MUR("Mauritian Rupee", "Mauritius", "MU"),
    MVR("Maldivian Rufiyaa", "Maldives", "MV"),
    MWK("Malawian Kwacha", "Malawi", "MW"),
    MXN("Mexican Peso", "Mexico", "MX"),
    MYR("Malaysian Ringgit", "Malaysia", "MY"),
    MZN("Mozambican Metical", "Mozambique", "MZ"),
    NAD("Namibian Dollar", "Namibia", "NA"),
    NGN("Nigerian Naira", "Nigeria", "NG"),
    NIO("Nicaraguan Córdoba", "Nicaragua", "NI"),
    NOK("Norwegian Krone", "Norway", "NO"),
    NPR("Nepalese Rupee", "Nepal", "NP"),
    NZD("New Zealand Dollar", "New Zealand", "NZ"),
    OMR("Omani Rial", "Oman", "OM"),
    PAB("Panamanian Balboa", "Panama", "PA"),
    PEN("Peruvian Sol", "Peru", "PE"),
    PGK("Papua New Guinean Kina", "Papua New Guinea", "PG"),
    PHP("Philippine Peso", "Philippines", "PH"),
    PKR("Pakistani Rupee", "Pakistan", "PK"),
    PLN("Polish Złoty", "Poland", "PL"),
    PYG("Paraguayan Guaraní", "Paraguay", "PY"),
    QAR("Qatari Riyal", "Qatar", "QA"),
    RON("Romanian Leu", "Romania", "RO"),
    RSD("Serbian Dinar", "Serbia", "RS"),
    RUB("Russian Ruble", "Russia", "RU"),
    RWF("Rwandan Franc", "Rwanda", "RW"),
    SAR("Saudi Riyal", "Saudi Arabia", "SA"),
    SBD("Solomon Islands Dollar", "Solomon Islands", "SB"),
    SCR("Seychellois Rupee", "Seychelles", "SC"),
    SDG("Sudanese Pound", "Sudan", "SD"),
    SEK("Swedish Krona", "Sweden", "SE"),
    SGD("Singapore Dollar", "Singapore", "SG"),
    SHP("Saint Helena Pound", "Saint Helena", "SH"),
    SLE("Sierra Leonean Leone", "Sierra Leone", "SL"),
    SOS("Somali Shilling", "Somalia", "SO"),
    SRD("Surinamese Dollar", "Suriname", "SR"),
    SSP("South Sudanese Pound", "South Sudan", "SS"),
    STN("São Tomé and Príncipe Dobra", "São Tomé and Príncipe", "ST"),
    SYP("Syrian Pound", "Syria", "SY"),
    SZL("Eswatini Lilangeni", "Eswatini", "SZ"),
    THB("Thai Baht", "Thailand", "TH"),
    TJS("Tajikistani Somoni", "Tajikistan", "TJ"),
    TMT("Turkmenistan Manat", "Turkmenistan", "TM"),
    TND("Tunisian Dinar", "Tunisia", "TN"),
    TOP("Tongan Paʻanga", "Tonga", "TO"),
    TRY("Turkish Lira", "Turkey", "TR"),
    TTD("Trinidad and Tobago Dollar", "Trinidad and Tobago", "TT"),
    TVD("Tuvaluan Dollar", "Tuvalu", "TV"),
    TWD("New Taiwan Dollar", "Taiwan", "TW"),
    TZS("Tanzanian Shilling", "Tanzania", "TZ"),
    UAH("Ukrainian Hryvnia", "Ukraine", "UA"),
    UGX("Ugandan Shilling", "Uganda", "UG"),
    USD("United States Dollar", "United States", "US"),
    UYU("Uruguayan Peso", "Uruguay", "UY"),
    UZS("Uzbekistani So'm", "Uzbekistan", "UZ"),
    VES("Venezuelan Bolívar Soberano", "Venezuela", "VE"),
    VND("Vietnamese Đồng", "Vietnam", "VN"),
    VUV("Vanuatu Vatu", "Vanuatu", "VU"),
    WST("Samoan Tālā", "Samoa", "WS"),
    XAF("Central African CFA Franc", "CEMAC", "XAF"),
    XCD("East Caribbean Dollar", "Organisation of Eastern Caribbean States", "XCD"),
    XDR("Special Drawing Rights", "International Monetary Fund", "XDR"),
    XOF("West African CFA franc", "CFA", "XOF"),
    XPF("CFP Franc", "Collectivités d'Outre-Mer", "XPF"),
    YER("Yemeni Rial", "Yemen", "YE"),
    ZAR("South African Rand", "South Africa", "ZA"),
    ZMW("Zambian Kwacha", "Zambia", "ZM"),
    ZWL("Zimbabwean Dollar", "Zimbabwe", "ZW");

    private final String currencyName;
    private final String country;
    private final String isoCountryCode;

    Currency(String currencyName, String country, String isoCountryCode) {
        this.currencyName = currencyName;
        this.country = country;
        this.isoCountryCode = isoCountryCode;
    }

    public String getCurrencyName() {
        return currencyName;
    }

    public String getCountry() {
        return country;
    }

    public String getIsoCountryCode() {
        return isoCountryCode;
    }
}

